name: Publish NuGet.org

on:
  workflow_dispatch:
    inputs:
      typeBuild:
        description: "É beta? (digite -beta)"
        required: false

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:
  deploy-package:
    runs-on: windows-latest

    steps:
      - name: "Checkout branch"
        uses: actions/checkout@main

      - name: "Set Variables"
        id: envs
        run: |
          echo "::set-output name=VERSION_PROJECT::1.0.${Env:GITHUB_RUN_NUMBER}"
          echo "::set-output name=VERSION_PACKAGE::1.0.${Env:GITHUB_RUN_NUMBER}${{ github.event.inputs.typeBuild }}"

      - name: "Variables Test"
        run: |
          echo Version: ${{ steps.envs.outputs.VERSION_PROJECT }}
          echo Version2: ${{ steps.envs.outputs.VERSION_PACKAGE }}

      - name: "Force url nuget"
        uses: fabriciomurta/ensure-nuget-source@v1
        with:
          name: "nuget.org"
          url: "https://api.nuget.org/v3/index.json"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Packages
        run: nuget restore .\src\Vip.CustomForm.sln
    
      - name: Build Solution
        run: |
          msbuild.exe .\src\Vip.CustomForm.sln /nologo /nr:false /p:platform="Any CPU" /p:configuration="Release"

      - name: Build Project
        run: dotnet build .\src\Vip.DFe.sln --configuration Release -p:Version=${{ steps.envs.outputs.VERSION_PROJECT }}

      - name: Nuget Add Source
        run: nuget sources Add -Name "nuget" -Source https://api.nuget.org/v3/index.json

      - name: Nuget SetAPIKey
        run: nuget setapikey ${{ secrets.NUGET_TOKEN }} -Source "nuget"

      - name: Generate pack Nuget
        run: nuget pack .\nuget\Vip.CustomForm.nuspec -Version ${{ steps.envs.outputs.VERSION_PACKAGE }}
        
      - name: Publish the package
        run: nuget push .\nuget\*.nupkg -source "nuget" -SkipDuplicate
    
#      - name: Publish Package
#        run: dotnet nuget push .\src\Vip.DFe\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}
